// Generated by gencpp from file segmentation/box_data.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_BOX_DATA_H
#define SEGMENTATION_MESSAGE_BOX_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segmentation
{
template <class ContainerAllocator>
struct box_data_
{
  typedef box_data_<ContainerAllocator> Type;

  box_data_()
    : box_data()  {
    }
  box_data_(const ContainerAllocator& _alloc)
    : box_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _box_data_type;
  _box_data_type box_data;





  typedef boost::shared_ptr< ::segmentation::box_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation::box_data_<ContainerAllocator> const> ConstPtr;

}; // struct box_data_

typedef ::segmentation::box_data_<std::allocator<void> > box_data;

typedef boost::shared_ptr< ::segmentation::box_data > box_dataPtr;
typedef boost::shared_ptr< ::segmentation::box_data const> box_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation::box_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation::box_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'segmentation': ['/home/zheng/pu_ws/src/segmentation/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::box_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::box_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::box_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::box_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::box_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::box_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation::box_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2f69ad0d9506dd9f7955546117df699";
  }

  static const char* value(const ::segmentation::box_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2f69ad0d9506dd9ULL;
  static const uint64_t static_value2 = 0xf7955546117df699ULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation::box_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation/box_data";
  }

  static const char* value(const ::segmentation::box_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation::box_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] box_data\n\
";
  }

  static const char* value(const ::segmentation::box_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation::box_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.box_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct box_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation::box_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation::box_data_<ContainerAllocator>& v)
  {
    s << indent << "box_data[]" << std::endl;
    for (size_t i = 0; i < v.box_data.size(); ++i)
    {
      s << indent << "  box_data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.box_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_MESSAGE_BOX_DATA_H
