// Generated by gencpp from file segmentation/processed_box_data.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_PROCESSED_BOX_DATA_H
#define SEGMENTATION_MESSAGE_PROCESSED_BOX_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segmentation
{
template <class ContainerAllocator>
struct processed_box_data_
{
  typedef processed_box_data_<ContainerAllocator> Type;

  processed_box_data_()
    : center()
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , angle(0.0)  {
    }
  processed_box_data_(const ContainerAllocator& _alloc)
    : center(_alloc)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _center_type;
  _center_type center;

   typedef double _length_type;
  _length_type length;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::segmentation::processed_box_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation::processed_box_data_<ContainerAllocator> const> ConstPtr;

}; // struct processed_box_data_

typedef ::segmentation::processed_box_data_<std::allocator<void> > processed_box_data;

typedef boost::shared_ptr< ::segmentation::processed_box_data > processed_box_dataPtr;
typedef boost::shared_ptr< ::segmentation::processed_box_data const> processed_box_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation::processed_box_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation::processed_box_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'segmentation': ['/home/zheng/pu_ws/src/segmentation/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::processed_box_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::processed_box_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::processed_box_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::processed_box_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::processed_box_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::processed_box_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation::processed_box_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "174b15346284f679bc3e127d60e5ccc7";
  }

  static const char* value(const ::segmentation::processed_box_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x174b15346284f679ULL;
  static const uint64_t static_value2 = 0xbc3e127d60e5ccc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation::processed_box_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation/processed_box_data";
  }

  static const char* value(const ::segmentation::processed_box_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation::processed_box_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] center\n\
float64 length\n\
float64 width\n\
float64 height\n\
float64 angle\n\
";
  }

  static const char* value(const ::segmentation::processed_box_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation::processed_box_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct processed_box_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation::processed_box_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation::processed_box_data_<ContainerAllocator>& v)
  {
    s << indent << "center[]" << std::endl;
    for (size_t i = 0; i < v.center.size(); ++i)
    {
      s << indent << "  center[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.center[i]);
    }
    s << indent << "length: ";
    Printer<double>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_MESSAGE_PROCESSED_BOX_DATA_H
