(cl:defpackage segmentation-msg
  (:use )
  (:export
   "<BOX_3D_DATA>"
   "BOX_3D_DATA"
   "<BOX_DATA>"
   "BOX_DATA"
   "<CYLINDER_DATA>"
   "CYLINDER_DATA"
   "<PROCESSED_BOX_3D_DATA>"
   "PROCESSED_BOX_3D_DATA"
   "<PROCESSED_BOX_DATA>"
   "PROCESSED_BOX_DATA"
   "<PROCESSED_CYLINDER_DATA>"
   "PROCESSED_CYLINDER_DATA"
   "<PROCESSED_SPHERE_DATA>"
   "PROCESSED_SPHERE_DATA"
   "<SPHERE_DATA>"
   "SPHERE_DATA"
  ))

