(cl:in-package segmentation-msg)
(cl:export '(CENTER-VAL
          CENTER
          LONGESTEDGELEN-VAL
          LONGESTEDGELEN
          MEDIANEDGELEN-VAL
          MEDIANEDGELEN
          SHORTESTEDGELEN-VAL
          SHORTESTEDGELEN
          LONGESTEDGEDIR-VAL
          LONGESTEDGEDIR
          MEDIANEDGEDIR-VAL
          MEDIANEDGEDIR
          SHORTESTEDGEDIR-VAL
          SHORTESTEDGEDIR
))